### ISSUE TITLE
Negative frequency?

### ISSUE THREAD

**Issue by mfalkvidd** [Jeija/renard-phy#3]
I'm getting this when trying to demodulate an uplink recording:
```
Estimating Frequency using 262144-length FFT
Signal Frequency: -196704.10 Hz
Mixing to Baseband with Costas Loop...
Low-pass Filtering...
Normalizing...
Finding Preamble(s)...
```
Any idea why I'm getting a negative frequency?

**Comment by Jeija** [comment]
I think it's because the recordings contain complex I/Q samples and the detected signal is simply to the left of the center frequency (the intermediate frequency). Negative frequencies make sense in this case.

If we have intermediate frequency IF and the frequency reported by the demodulation script is f, then the true signal frequency is IF + f, which can be smaller than IF for negative f.

**Comment by mfalkvidd** [comment]
I see. Thanks for explaining.
